name = "CommonMark"
uuid = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
authors = ["Michael Hatherly"]
version = "0.6.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[compat]
Crayons = "4"
JSON = "0.20, 0.21"
URIParser = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[targets]
test = ["Test", "JSON", "Pkg", "YAML"]
