[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[sources]
CommonMark = {path = ".."}

[compat]
Documenter = "1"
