[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[sources]
CommonMark = {path = ".."}

[compat]
Documenter = "1"
